/**
 * Comprehensive Permissions Enum for HMS
 * Covers all modules and operations
 */
export enum Permission {
  // ==================================================
  // TENANT MANAGEMENT
  // ==================================================
  TENANT_CREATE = 'TENANT_CREATE',
  TENANT_READ = 'TENANT_READ',
  VIEW_TENANT = 'VIEW_TENANT', // Alias
  TENANT_UPDATE = 'TENANT_UPDATE',
  UPDATE_TENANT = 'UPDATE_TENANT', // Alias
  TENANT_DELETE = 'TENANT_DELETE',
  MANAGE_TENANT_BILLING = 'MANAGE_TENANT_BILLING',

  // ==================================================
  // USER MANAGEMENT
  // ==================================================
  USER_CREATE = 'USER_CREATE',
  CREATE_USERS = 'CREATE_USERS', // Alias
  USER_READ = 'USER_READ',
  VIEW_USERS = 'VIEW_USERS', // Alias
  USER_UPDATE = 'USER_UPDATE',
  UPDATE_USERS = 'UPDATE_USERS', // Alias
  USER_DELETE = 'USER_DELETE',

  // ==================================================
  // PATIENT MANAGEMENT
  // ==================================================
  PATIENT_CREATE = 'PATIENT_CREATE',
  CREATE_PATIENTS = 'CREATE_PATIENTS', // Alias
  PATIENT_READ = 'PATIENT_READ',
  VIEW_PATIENTS = 'VIEW_PATIENTS', // Alias
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  UPDATE_PATIENTS = 'UPDATE_PATIENTS', // Alias
  PATIENT_DELETE = 'PATIENT_DELETE',
  VIEW_PATIENT_DEMOGRAPHICS = 'VIEW_PATIENT_DEMOGRAPHICS',
  UPDATE_PATIENT_DEMOGRAPHICS = 'UPDATE_PATIENT_DEMOGRAPHICS',
  VIEW_PATIENT_HISTORY = 'VIEW_PATIENT_HISTORY',
  EXPORT_PATIENTS = 'EXPORT_PATIENTS',

  // ==================================================
  // APPOINTMENTS
  // ==================================================
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  CREATE_APPOINTMENTS = 'CREATE_APPOINTMENTS', // Alias
  APPOINTMENT_READ = 'APPOINTMENT_READ',
  VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS', // Alias
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  UPDATE_APPOINTMENTS = 'UPDATE_APPOINTMENTS', // Alias
  APPOINTMENT_DELETE = 'APPOINTMENT_DELETE',
  CANCEL_APPOINTMENTS = 'CANCEL_APPOINTMENTS',
  VIEW_SCHEDULE = 'VIEW_SCHEDULE',
  MANAGE_SCHEDULE = 'MANAGE_SCHEDULE',
  BOOK_ONLINE = 'BOOK_ONLINE',

  // ==================================================
  // MEDICAL RECORDS
  // ==================================================
  MEDICAL_RECORD_CREATE = 'MEDICAL_RECORD_CREATE',
  CREATE_MEDICAL_RECORDS = 'CREATE_MEDICAL_RECORDS', // Alias
  MEDICAL_RECORD_READ = 'MEDICAL_RECORD_READ',
  VIEW_MEDICAL_RECORDS = 'VIEW_MEDICAL_RECORDS', // Alias
  MEDICAL_RECORD_UPDATE = 'MEDICAL_RECORD_UPDATE',
  UPDATE_MEDICAL_RECORDS = 'UPDATE_MEDICAL_RECORDS', // Alias
  MEDICAL_RECORD_DELETE = 'MEDICAL_RECORD_DELETE',
  DELETE_MEDICAL_RECORDS = 'DELETE_MEDICAL_RECORDS', // Alias
  VIEW_SENSITIVE_RECORDS = 'VIEW_SENSITIVE_RECORDS',
  SIGN_MEDICAL_RECORDS = 'SIGN_MEDICAL_RECORDS',

  // ==================================================
  // ENCOUNTERS / CONSULTATIONS
  // ==================================================
  VIEW_ENCOUNTERS = 'VIEW_ENCOUNTERS',
  CREATE_ENCOUNTERS = 'CREATE_ENCOUNTERS',
  UPDATE_ENCOUNTERS = 'UPDATE_ENCOUNTERS',
  CLOSE_ENCOUNTERS = 'CLOSE_ENCOUNTERS',
  VIEW_CONSULTATION_NOTES = 'VIEW_CONSULTATION_NOTES',
  CREATE_CONSULTATION_NOTES = 'CREATE_CONSULTATION_NOTES',

  // ==================================================
  // PRESCRIPTIONS
  // ==================================================
  PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE',
  CREATE_PRESCRIPTIONS = 'CREATE_PRESCRIPTIONS', // Alias
  PRESCRIPTION_READ = 'PRESCRIPTION_READ',
  VIEW_PRESCRIPTIONS = 'VIEW_PRESCRIPTIONS', // Alias
  PRESCRIPTION_UPDATE = 'PRESCRIPTION_UPDATE',
  UPDATE_PRESCRIPTIONS = 'UPDATE_PRESCRIPTIONS', // Alias
  PRESCRIPTION_DELETE = 'PRESCRIPTION_DELETE',
  CANCEL_PRESCRIPTIONS = 'CANCEL_PRESCRIPTIONS',
  DISPENSE_PRESCRIPTIONS = 'DISPENSE_PRESCRIPTIONS',
  DISPENSE_MEDICATION = 'DISPENSE_MEDICATION',

  // ==================================================
  // LAB ORDERS & RESULTS
  // ==================================================
  LAB_ORDER_CREATE = 'LAB_ORDER_CREATE',
  CREATE_LAB_ORDERS = 'CREATE_LAB_ORDERS', // Alias
  LAB_ORDER_READ = 'LAB_ORDER_READ',
  VIEW_LAB_ORDERS = 'VIEW_LAB_ORDERS', // Alias
  LAB_ORDER_UPDATE = 'LAB_ORDER_UPDATE',
  UPDATE_LAB_ORDERS = 'UPDATE_LAB_ORDERS', // Alias
  LAB_ORDER_DELETE = 'LAB_ORDER_DELETE',
  VIEW_LAB_RESULTS = 'VIEW_LAB_RESULTS',
  ENTER_LAB_RESULTS = 'ENTER_LAB_RESULTS',
  VERIFY_LAB_RESULTS = 'VERIFY_LAB_RESULTS',
  APPROVE_LAB_RESULTS = 'APPROVE_LAB_RESULTS',
  PRINT_LAB_REPORTS = 'PRINT_LAB_REPORTS',
  MANAGE_LAB_TESTS = 'MANAGE_LAB_TESTS',
  COLLECT_SAMPLES = 'COLLECT_SAMPLES',
  TRACK_SAMPLES = 'TRACK_SAMPLES',

  // ==================================================
  // RADIOLOGY
  // ==================================================
  RADIOLOGY_ORDER_CREATE = 'RADIOLOGY_ORDER_CREATE',
  CREATE_RADIOLOGY_ORDERS = 'CREATE_RADIOLOGY_ORDERS', // Alias
  RADIOLOGY_ORDER_READ = 'RADIOLOGY_ORDER_READ',
  VIEW_RADIOLOGY_ORDERS = 'VIEW_RADIOLOGY_ORDERS', // Alias
  RADIOLOGY_ORDER_UPDATE = 'RADIOLOGY_ORDER_UPDATE',
  RADIOLOGY_ORDER_DELETE = 'RADIOLOGY_ORDER_DELETE',
  VIEW_RADIOLOGY_IMAGES = 'VIEW_RADIOLOGY_IMAGES',
  UPLOAD_RADIOLOGY_IMAGES = 'UPLOAD_RADIOLOGY_IMAGES',
  PERFORM_RADIOLOGY_EXAM = 'PERFORM_RADIOLOGY_EXAM',
  REPORT_RADIOLOGY = 'REPORT_RADIOLOGY',
  APPROVE_RADIOLOGY_REPORT = 'APPROVE_RADIOLOGY_REPORT',

  // ==================================================
  // PHARMACY & INVENTORY
  // ==================================================
  PHARMACY_ORDER_CREATE = 'PHARMACY_ORDER_CREATE',
  PHARMACY_ORDER_READ = 'PHARMACY_ORDER_READ',
  PHARMACY_ORDER_UPDATE = 'PHARMACY_ORDER_UPDATE',
  PHARMACY_ORDER_DELETE = 'PHARMACY_ORDER_DELETE',
  VIEW_PHARMACY_INVENTORY = 'VIEW_PHARMACY_INVENTORY',
  MANAGE_PHARMACY_INVENTORY = 'MANAGE_PHARMACY_INVENTORY',
  VIEW_MEDICATION_CATALOG = 'VIEW_MEDICATION_CATALOG',
  MANAGE_MEDICATION_CATALOG = 'MANAGE_MEDICATION_CATALOG',
  CREATE_PURCHASE_ORDERS = 'CREATE_PURCHASE_ORDERS',
  APPROVE_PURCHASE_ORDERS = 'APPROVE_PURCHASE_ORDERS',
  MANAGE_DRUG_SUPPLIERS = 'MANAGE_DRUG_SUPPLIERS',
  VIEW_DRUG_EXPIRY = 'VIEW_DRUG_EXPIRY',
  MANAGE_DRUG_PRICING = 'MANAGE_DRUG_PRICING',

  // ==================================================
  // INVENTORY MANAGEMENT
  // ==================================================
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_READ = 'INVENTORY_READ',
  VIEW_INVENTORY = 'VIEW_INVENTORY', // Alias
  INVENTORY_UPDATE = 'INVENTORY_UPDATE',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY', // Alias
  INVENTORY_DELETE = 'INVENTORY_DELETE',
  CREATE_STOCK_REQUESTS = 'CREATE_STOCK_REQUESTS',
  APPROVE_STOCK_REQUESTS = 'APPROVE_STOCK_REQUESTS',
  TRACK_INVENTORY_MOVEMENT = 'TRACK_INVENTORY_MOVEMENT',
  MANAGE_SUPPLIERS = 'MANAGE_SUPPLIERS',
  VIEW_INVENTORY_ALERTS = 'VIEW_INVENTORY_ALERTS',

  // ==================================================
  // BILLING & INVOICES
  // ==================================================
  INVOICE_CREATE = 'INVOICE_CREATE',
  CREATE_INVOICES = 'CREATE_INVOICES', // Alias
  INVOICE_READ = 'INVOICE_READ',
  VIEW_BILLING = 'VIEW_BILLING', // Alias
  INVOICE_UPDATE = 'UPDATE_INVOICES',
  UPDATE_INVOICES = 'UPDATE_INVOICES', // Alias
  INVOICE_DELETE = 'INVOICE_DELETE',
  VOID_INVOICES = 'VOID_INVOICES',
  MANAGE_PRICING = 'MANAGE_PRICING',
  APPLY_DISCOUNTS = 'APPLY_DISCOUNTS',

  // ==================================================
  // PAYMENTS
  // ==================================================
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PROCESS_PAYMENTS = 'PROCESS_PAYMENTS', // Alias
  PAYMENT_READ = 'PAYMENT_READ',
  VIEW_PAYMENTS = 'VIEW_PAYMENTS', // Alias
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  PAYMENT_DELETE = 'PAYMENT_DELETE',
  REFUND_PAYMENTS = 'REFUND_PAYMENTS',
  MANAGE_PAYMENT_METHODS = 'MANAGE_PAYMENT_METHODS',
  VIEW_RECEIPTS = 'VIEW_RECEIPTS',
  PRINT_RECEIPTS = 'PRINT_RECEIPTS',

  // ==================================================
  // INSURANCE
  // ==================================================
  INSURANCE_CLAIM_CREATE = 'INSURANCE_CLAIM_CREATE',
  CREATE_INSURANCE_CLAIMS = 'CREATE_INSURANCE_CLAIMS', // Alias
  INSURANCE_CLAIM_READ = 'INSURANCE_CLAIM_READ',
  VIEW_INSURANCE = 'VIEW_INSURANCE', // Alias
  INSURANCE_CLAIM_UPDATE = 'INSURANCE_CLAIM_UPDATE',
  SUBMIT_INSURANCE_CLAIMS = 'SUBMIT_INSURANCE_CLAIMS',
  TRACK_INSURANCE_CLAIMS = 'TRACK_INSURANCE_CLAIMS',
  APPROVE_INSURANCE_CLAIMS = 'APPROVE_INSURANCE_CLAIMS',
  VERIFY_INSURANCE_ELIGIBILITY = 'VERIFY_INSURANCE_ELIGIBILITY',

  // ==================================================
  // IPD (INPATIENT)
  // ==================================================
  IPD_ADMISSION_CREATE = 'IPD_ADMISSION_CREATE',
  CREATE_IPD_ADMISSION = 'CREATE_IPD_ADMISSION', // Alias
  IPD_ADMISSION_READ = 'IPD_ADMISSION_READ',
  VIEW_IPD_RECORDS = 'VIEW_IPD_RECORDS', // Alias
  IPD_ADMISSION_UPDATE = 'IPD_ADMISSION_UPDATE',
  UPDATE_IPD_RECORDS = 'UPDATE_IPD_RECORDS', // Alias
  IPD_DISCHARGE = 'IPD_DISCHARGE',
  DISCHARGE_PATIENT = 'DISCHARGE_PATIENT', // Alias
  VIEW_BEDS = 'VIEW_BEDS',

  // ==================================================
  // OPD (OUTPATIENT)
  // ==================================================
  VIEW_OPD_QUEUE = 'VIEW_OPD_QUEUE',
  MANAGE_OPD_QUEUE = 'MANAGE_OPD_QUEUE',

  // ==================================================
  // NURSING
  // ==================================================
  VIEW_NURSING_NOTES = 'VIEW_NURSING_NOTES',
  CREATE_NURSING_NOTES = 'CREATE_NURSING_NOTES',
  UPDATE_NURSING_NOTES = 'UPDATE_NURSING_NOTES',
  VIEW_VITALS = 'VIEW_VITALS',
  RECORD_VITALS = 'RECORD_VITALS',
  ADMINISTER_MEDICATION = 'ADMINISTER_MEDICATION',

  // ==================================================
  // EMERGENCY
  // ==================================================
  EMERGENCY_ACCESS = 'EMERGENCY_ACCESS',

  // ==================================================
  // SURGERY
  // ==================================================
  SURGERY_CREATE = 'SURGERY_CREATE',
  SURGERY_READ = 'SURGERY_READ',
  SURGERY_UPDATE = 'SURGERY_UPDATE',

  // ==================================================
  // STAFF MANAGEMENT
  // ==================================================
  VIEW_STAFF = 'VIEW_STAFF',
  MANAGE_STAFF = 'MANAGE_STAFF',
  VIEW_ATTENDANCE = 'VIEW_ATTENDANCE',
  MANAGE_ATTENDANCE = 'MANAGE_ATTENDANCE',
  VIEW_PAYROLL = 'VIEW_PAYROLL',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',
  VIEW_LEAVE_REQUESTS = 'VIEW_LEAVE_REQUESTS',
  APPROVE_LEAVE_REQUESTS = 'APPROVE_LEAVE_REQUESTS',
  MANAGE_SHIFTS = 'MANAGE_SHIFTS',

  // ==================================================
  // TELEMEDICINE
  // ==================================================
  TELEMEDICINE_CREATE = 'TELEMEDICINE_CREATE',
  TELEMEDICINE_JOIN = 'TELEMEDICINE_JOIN',
  TELEMEDICINE_READ = 'TELEMEDICINE_READ',

  // ==================================================
  // MESSAGES & NOTIFICATIONS
  // ==================================================
  MESSAGE_SEND = 'MESSAGE_SEND',
  SEND_MESSAGES = 'SEND_MESSAGES', // Alias
  MESSAGE_READ = 'MESSAGE_READ',
  VIEW_MESSAGES = 'VIEW_MESSAGES', // Alias
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  SEND_SMS = 'SEND_SMS',
  SEND_EMAIL = 'SEND_EMAIL',

  // ==================================================
  // DOCUMENTS
  // ==================================================
  VIEW_DOCUMENTS = 'VIEW_DOCUMENTS',
  UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
  DOWNLOAD_DOCUMENTS = 'DOWNLOAD_DOCUMENTS',

  // ==================================================
  // REPORTS & ANALYTICS
  // ==================================================
  REPORT_VIEW = 'REPORT_VIEW',
  VIEW_REPORTS = 'VIEW_REPORTS', // Alias
  REPORT_EXPORT = 'REPORT_EXPORT',
  EXPORT_REPORTS = 'EXPORT_REPORTS', // Alias
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  VIEW_CLINICAL_DASHBOARDS = 'VIEW_CLINICAL_DASHBOARDS',
  VIEW_OPERATIONAL_DASHBOARDS = 'VIEW_OPERATIONAL_DASHBOARDS',
  VIEW_FINANCIAL_DASHBOARDS = 'VIEW_FINANCIAL_DASHBOARDS',
  EXPORT_DATA = 'EXPORT_DATA',

  // ==================================================
  // SYSTEM ADMINISTRATION
  // ==================================================
  SYSTEM_SETTINGS_READ = 'SYSTEM_SETTINGS_READ',
  VIEW_SYSTEM_SETTINGS = 'VIEW_SYSTEM_SETTINGS', // Alias
  SYSTEM_SETTINGS_WRITE = 'SYSTEM_SETTINGS_WRITE',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS', // Alias
  AUDIT_LOG_READ = 'AUDIT_LOG_READ',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS', // Alias
  MANAGE_AUDIT_LOGS = 'MANAGE_AUDIT_LOGS',
  MANAGE_INTEGRATIONS = 'MANAGE_INTEGRATIONS',
  BACKUP_DATA = 'BACKUP_DATA',

  // ==================================================
  // SPECIAL PERMISSIONS
  // ==================================================
  ALL = 'ALL', // Super admin only
  MANAGE_PLATFORM = 'MANAGE_PLATFORM',
}
